### PR TITLE
remove ads and tracking

### PR DESCRIPTION
**Pull request by vladikoff**
@dmethvin review?

### CODE REVIEW

**Comment by dmethvin** [comment]
So you (the team) don't have control over these ads? Who runs that account?

**Comment by vladikoff** [comment]
@dmethvin Ben told me that Jory is gonna email you about that

**Comment by dmethvin** [comment]
She did, and I said it's up to you guys. I just referee. If there are paying ads in rotation on that site or ones that promote for-profit companies then I might have concerns. I'd have to turn off adblock to know though :smiling_imp:

**Comment by jorydotcom** [comment]
Hi @vladikoff - I don't have your email address else I would've emailed you & @dmethvin simultaneously! In any case, here's what I sent Dave:

> It's an OS ad server Bocoup is running, which promotes other OSS projects, the jQuery Events, free learning resources, and other front end conferences. It is not revenue generating. If there's a problematic ad I'm sure Adam (@ajpiano) will be happy to take it down. If there is something the core team or jQuery would like to promote, we can certainly do that as well.

Happy to get you set up on it, change settings, or w/e - we (@cowboy & @tkellen) just didn't know there was an issue here and wanted to talk about it if that was the case! I'm jory@bocoup.com if you prefer email :smile:

**Comment by vladikoff** [comment]
Okay if @dmethvin and @ajpiano are okay with this then we can keep this. Thanks!

**Comment by ajpiano** [comment]
Thanks!

**Pull request closed without merging**
