### PR TITLE
Added new SVG badge using shields.io style guide

### PR DESCRIPTION
**Pull request by andersevenrud**
Ref: https://github.com/gruntjs/grunt/issues/1365#issuecomment-160183606

### CODE REVIEW

**Comment by vladikoff** [comment]
The attached svg can be optimized to reduce size: 

use svgo to do that. `Optimised file size: 2.2 kB (81.4%)`

Also why does the PNG look so pixelated in the preview: http://v14d.com/i/56589f31e4a4d.jpg

**Comment by andersevenrud** [comment]
@vladikoff Fixed optimization.

> Also why does the PNG look so pixelated in the preview

How are you viewing it ? If it is on github it is because images are loaded via a proxy service that dramaticaly reduces quality.

This is how it looks "raw": https://github.com/andersevenrud/gruntjs.com/blob/master/misc/badge.svg

**Comment by JKAussieSkater** [comment]
Looks great! :+1:

Have a few questions though.

0. Shouldn't this be pulled into the [__`src/cdn/`__](https://github.com/gruntjs/gruntjs.com/tree/master/src/cdn) folder, to be in the same location as the old badge?
0. Should this replace the original badge entirely, or simply be presented as an additional option on the [Built with Grunt Badge](https://github.com/gruntjs/grunt-docs/blob/master/Built-with-Grunt-Badge.md) page?
0. [Can I use](http://caniuse.com/#feat=svg) indicates that using SVG graphics within browsers is acceptable:
 0. @vladikoff, is a PNG version necessary?
  0. If so, shall I generate a high-quality PNG (with GIMP?) to pair with the SVG version?

**Comment by andersevenrud** [comment]
@JKAussieSkater 

1. Probably
2. It'd be cool if this was to become the default, and that's how it sounded in the issue(s)
3. SVG support is pretty good, yeah

I first made the issue, then this PR, but it never got anywhere. Been waiting for feedback :)

**Comment by vladikoff** [comment]
> @vladikoff, is a PNG version necessary?

No, kill it

**Comment by vladikoff** [comment]
> No, kill it

We will still host it but should not recommend it anymore

**Comment by JKAussieSkater** [comment]
Okay, great!
@andersevenrud, change the folder to `src/cdn`, and then we can close this PR once and for all! :+1:

**Comment by andersevenrud** [comment]
@JKAussieSkater Moved to `src/cdn/builtwith.svg`

**Comment by JKAussieSkater** [comment]
Thanks!

**Comment by andersevenrud** [comment]
Sure thang! :)

**Comment by vladikoff** [comment]
We have some CDN configuration that either directories or single files, we have to wait until we redeploy the site and then try accessing this new file via the CDN. After that we can update the docs with the new svg badge

**Pull request merged**
