### PR TITLE
Changed the Twitter Logo in the main page

### PR DESCRIPTION
**Pull request by cack195**
Changed the twitter logo to X in the main page.

### CODE REVIEW

**Comment by cack195** [comment]
I have changed the logo to X for the twitter icon in the home page and updated package.json

**Comment by cack195** [comment]
image

**Comment by XhmikosR** [comment]
You have unrelated changes....

**Comment by cack195** [comment]
I'm sorry 
I'll try to make some meaningful contribution..
Thank you for your feedback

**Pull request closed without merging**
